### ISSUE TITLE
Can you advise on how to load the checkpoints from RLLib

### ISSUE THREAD

**Issue by wirtsi** [hugocen/freqtrade-gym#13]
RLLib seems to store the checkpoints under ~/ray_results ... but how do I load them for backtesting, this seems to be a different format?

**Comment by harry0731** [comment]
You can check out [LoadRLModel.py)](https://github.com/harry0731/freqtrade-gym/blob/master/LoadRLModel.py)
And follow the [rllib guide](https://docs.ray.io/en/master/rllib-training.html#accessing-model-state) to replace the part of loading models.
