### ISSUE TITLE
The best backtests results

### ISSUE THREAD

**Issue by xsa-dev** [hugocen/freqtrade-gym#14]
Hello, buds

I am test this on Tensorflow version and my results of backtests is not good enough for dry run mode tests. You can see it attached file: [ft_rl_results-default.txt](https://github.com/harry0731/freqtrade-gym/files/6444592/ft_rl_results-default.txt)

Whats your results?

**Comment by hugocen** [comment]
Yea, my results with deep reinforcement learning are not so good either.
But I got some okish results using NEAT algorithms.
We still need a lot of tunning and research to make this work.

**Comment by evo11x** [comment]
can you post the NEAT implementation with this strategy?

**Comment by hugocen** [comment]
@evo11x 
I updated the [neat_trade.py](https://github.com/hugocen/freqtrade-gym/blob/master/neat_trade.py) for traing.
And [Neat_RL.py](https://github.com/hugocen/freqtrade-gym/blob/master/Neat_RL.py) for loading the model.
Sorry, but it's kinda sloppy.
