### ISSUE TITLE
'IndicatorforRL' object has no attribute 'ohlcvdata_to_dataframe'

### ISSUE THREAD

**Issue by evo11x** [hugocen/freqtrade-gym#18]
I have installed the files in freqtrade and get this error in freqtradegym.py at line 45, when I try to run deep_rl.py

Exception has occurred: AttributeError
'IndicatorforRL' object has no attribute 'ohlcvdata_to_dataframe'

I don't know from where comes this ohlcvdata_to_dataframe function, I cannot find it anywhere declared...

**Comment by evo11x** [comment]
I fixed it by changing the line to
 preprocessed = ohlcv_to_dataframe(data, pair=pair, timeframe=self.timeframe)

but now I get this error

Exception has occurred: KeyError
'date'
  File "freqtrade-develop\freqtrade\data\converter.py", line 141, in trim_dataframe
    df = df.loc[df[df_date_col] >= start, :]
  File "freqtrade-develop\freqtradegym.py", line 59, in __init__
    dfs.append(trim_dataframe(df, timerange))
  File "freqtrade-develop\deep_rl.py", line 13, in <module>
    env = TradingEnv(config)

**Comment by perrolokos** [comment]
Use freqtrade 2020.11 version
