### ISSUE TITLE
The file model could not be found

### ISSUE THREAD

**Issue by NL647** [hugocen/freqtrade-gym#19]
Hello, thanks for sharing the project .
I get an error running: python deep_rl.py

`   raise ValueError("Error: the file {} could not be found".format(load_path))
ValueError: Error: the file model could not be found`

Any idea how to fix it?

Thanks

**Comment by perrolokos** [comment]
I had created a blank file model.zip, however using the version of freqtrade 2020.11 it does not give any error

**Comment by NL647** [comment]
Hello,
Thank you for the help it solved my issue.

**Comment by sn3fru** [comment]
> I had created a blank file model.zip, however using the version of freqtrade 2020.11 it does not give any error

@perrolokos could you explain it to me in more detail. I didn't understand what you meant and I have the same problem. Thanks.

**Comment by perrolokos** [comment]
cd freqtrade
touch model.zip
